### PR TITLE
Feature wireframe readme

### PR DESCRIPTION
**Pull request by tfbielawski**
## Description
This  README file is intended to explain the reason for including wireframes in the repo, and it has instructions for updates to the wireframes folder and the README.

## Type of change

- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said change

https://user-images.githubusercontent.com/70349084/139925493-9a3a399d-7458-4c7a-b68a-4e2253053e63.mp4

s

### CODE REVIEW

**Review by kennymiesner — APPROVED** [review]
This seems like a great way to keep the design progress organized.

**Review by VAIBHAVIBALAR — APPROVED** [review]
Amazing work. creating a readme is a great help to direct the entire application roadmap perfectly. Also defining each terms is worth appreciation.

**Review by mariuscmoldovan — APPROVED** [review]
Nice work! A readme for the wireframes will offer more details for the next teams to better understand the user flow.

**Comment by Tereamarie** [comment]
Looks great very clean creating the README.md is very helpful to other developers in the future very descriptive.

**Pull request merged**
