### PR TITLE
wired navbar and components for simple feature implementation and tes…

### PR DESCRIPTION
**Pull request by Broveku**
…ting

## Description

{{PAIR PROGRAMMED WITH JOSH GEARHEART}}}

wired up a simple navbar and its corresponding components for easy feature implementation and testing

Fixes # (issue)

## Type of change
- [x] New feature (non-breaking change which adds functionality)
## Checklist:

- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have removed unnecessary comments/console logs from my code
- x[ ] I have made corresponding changes to the documentation if necessary (optional)
- [x ] My changes generate no new warnings
- [x ] I have checked my code and corrected any misspellings
- [x ] No duplicate code left within changed files
- [x ] Size of pull request kept to a minimum
- [x ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by Broveku** [comment]
https://user-images.githubusercontent.com/84815843/140294632-22169033-a4a3-43f8-8c33-3b015fb8f50f.mp4

**Review by TrevourGuild — APPROVED** [review]
This is a very great and helpful feature! It will allow us to be able to navigate the app more smoothly when working on the various components. Great work!

**Review by kennymiesner — APPROVED** [review]
Nav scaffolding is clean and concise. Walkthrough of code and front-end was very helpful. Great work!

**Review by jessejohns-1 — APPROVED** [review]
Wonderful work! concise video as well. This implementation is very beneficial for allowing quick endpoints and components to be connected for future tickets!

**Review by VAIBHAVIBALAR — APPROVED** [review]
Super clean. This is going to be much helpful for the future developers and organize things in a better way.

**Review by tfbielawski — APPROVED** [review]
Nice walkthrough. The code was a little small, but you explained it well. Nice work wiring in those components for future scaling.

**Comment by paulstgermain** [comment]
The only thing I noticed with this Routes/Navigation setup is that there are no buttons available to click to go back to the Home page - always ensure the user can move freely about the website no matter where on the site they are, if they're authenticated, of course! 😉

**Comment by Broveku** [comment]
> The only thing I noticed with this Routes/Navigation setup is that there are no buttons available to click to go back to the Home page - always ensure the user can move freely about the website no matter where on the site they are, if they're authenticated, of course! 😉

Hadnt even crossed my mind, thanks for the reminder!

**Pull request merged**
