### PR TITLE
Feature/create super admin from

### PR DESCRIPTION
**Pull request by RaphaelHebert**
## Description

Added superadmin from to aloow superAdmins to create superAdmins and UpdateProfile form to find, update and delete users

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [] I have removed unnecessary comments/console logs from my code
- [] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by tfbielawski — APPROVED** [review]
Nice work, lots of commits. I noticed a few sections of code that are commented out, and there comments in various places. Was that intentional?

**Review by iwood55 — APPROVED** [review]
Code looks clean. The commented out portions describes well what you are doing and waiting for on the crud operations.

**Review by taylorkangillescas — APPROVED** [review]
Code looks good. I reviewed the changes and see no issues. Good job.

**Comment by johanna-rodriguez** [comment]
Great work! changes seems good.

**Pull request merged**
