### PR TITLE
Updates meta title and description

### PR DESCRIPTION
**Pull request by kennymiesner**
## Description

Updates meta title and description from the create-react-app defaults.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

https://www.loom.com/share/093e719bdc3c4fe68991e38729596571

### CODE REVIEW

**Review by tfbielawski — APPROVED** [review]
Video is succinct and effective. Not much else to say!

**Review by mariuscmoldovan — APPROVED** [review]
Good catch in updating the meta title.

**Review by VAIBHAVIBALAR — APPROVED** [review]
it was a great catch. It seems now we are putting things into place

**Comment by johanna-rodriguez** [comment]
Great attention to detail.

**Pull request merged**
