### PR TITLE
Features/navbar/styled

### PR DESCRIPTION
**Pull request by tfbielawski**
## Description

I styled the existing code for the navbar component, and I created a footer component. Both components are styled in accordance with approved wireframe design.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said change

https://user-images.githubusercontent.com/70349084/141171789-24503406-039a-4fd1-b46c-3bb009e57c70.mp4

s

### CODE REVIEW

**Comment by Tereamarie** [comment]
Great review of what you did very helpful explanations. Looks Great

**Review by kennymiesner — APPROVED** [review]
Styled header and footer are really bringing the design together. The only thing I noticed is that I'm getting a few warnings in `Files changed` for "img elements must have an alt prop, either with meaningful text, or an empty string for decorative images." We may need to add those in for accessibility.

**Comment by tfbielawski** [comment]
> Styled header and footer are really bringing the design together. The only thing I noticed is that I'm getting a few warnings in `Files changed` for "img elements must have an alt prop, either with meaningful text, or an empty string for decorative images." We may need to add those in for accessibility.

Dang! I forgot the alt tags

**Comment by tfbielawski** [comment]
> > Styled header and footer are really bringing the design together. The only thing I noticed is that I'm getting a few warnings in `Files changed` for "img elements must have an alt prop, either with meaningful text, or an empty string for decorative images." We may need to add those in for accessibility.
> 
> Dang! I forgot the alt tags

Added alt descriptions where needed and pushed changes. Thanks!

**Review by mariuscmoldovan — APPROVED** [review]
Nice design for the navigation and footer bar.

**Review by TrevourGuild — APPROVED** [review]
Great job on the styling for the navbar and the footer! It looks clean and concise. I also liked that you used a css file for the styling. I think doing it this way would ensure that people are not stepping on eachothers toes. Great job!

**Review by JorshuaG — APPROVED** [review]
Code is clean and concise. Great job on the styling, it is consistent with the stakeholders existing website.

**Review by taylorkangillescas — APPROVED** [review]
Great styling on the navbar and the footer. Great implementation of the new logo. Good job.

**Pull request merged**
