### PR TITLE
Update favicon

### PR DESCRIPTION
**Pull request by kennymiesner**
## Description

Updated the favicon file to the new logo found on underdogdevs.org.
https://trello.com/c/sRM033x9/38-create-a-favicon-of-underdog-devs-logo-and-add-it-to-our-project

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

https://www.loom.com/share/1bc88c92b72647a6bdbc9be4e1df32bf

### CODE REVIEW

**Review by VAIBHAVIBALAR — APPROVED** [review]
The new logo looks great and it defines the purpose properly. Great start for actual implementation

**Review by JorshuaG — APPROVED** [review]
New logo looks great, great job getting that updated quickly. Being ahead of that will save a lot of time updating existing use cases.

**Review by jessejohns-1 — APPROVED** [review]
Perfect Addition to the site clean and well done. Thank you for your time and effort!

**Review by jessejohns-1 — COMMENTED** [review]
Ensure to edit the documentation on your pull request under
Type of change<
Please delete options that are not relevant. <  
I believe this is preventing your pr from being merged.

**Comment by johanna-rodriguez** [comment]
Nice addition. I believe that logo is more attractive. Will improve the look and feel of the application.

**Comment by Broveku** [comment]
Well done getting our product inline with the main website by matching logos

**Pull request merged**
